key1 = "sk-MB_JC01MO5_ChgFLXdQ-Hxt98t-5O3ckVy9dQoo6JDT3BlbkFJ3u3phNlVk_FhpHG2hhPRlVr6bR1IDX3YA-xJAChU4A"

cohere_key = "Py72cvoJi5UMFGoBwkzc8rvdOKvlFU0m4G8HRuZ7"

mistral_key = "TSchOI8Q88hrJBSgwn9aBSfCPJpMTj1z"